apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: org-data
spec:
  type: url
  targets:
    - https://github.com/keithralphs/DiscoveryTest/blob/main/subfolder/locations/entities/sponge.yaml
    - https://github.com/keithralphs/DiscoveryTest/blob/main/subfolder/locations/entities/subscriptions.yaml
